security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_STUDENT:               [ROLE_USER]
        ROLE_COMPANY_STAFF:         [ROLE_USER]
        ROLE_COMPANY_STAFF_ADMIN:   [ROLE_COMPANY_STAFF]
        ROLE_HEI_STAFF:             [ROLE_USER]
        ROLE_HEI_STAFF_ADMIN:       [ROLE_HEI_STAFF]
        ROLE_SUPER_ADMIN:           [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register_student, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register_company, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/student, role: ROLE_STUDENT }
        - { path: ^/company, role: ROLE_COMPANY_STAFF }
        - { path: ^/hei, role: ROLE_HEI_STAFF }
        - { path: ^/hei, role: ROLE_HEI_STAFF }
        - { path: ^/document, role: ROLE_USER }

 